######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 25 06:34:07 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += demo_ui.h
SOURCES += demo_main.cpp
